# Font configuration
font_family      BlexMono Nerd Font
font_size        10.0

# Window appearance
background_opacity 1.00

# Padding: top right bottom left (4px vertical, 4px horizontal)
window_padding_width 4 4

# Eliminate residual vertical dead space around terminal cells
placement_strategy top-left



# BEGIN_KITTY_THEME
# 1984 Dark
include current-theme.conf
# END_KITTY_THEME