#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# Check for each display
my_laptop_external_monitor=$(xrandr --query | grep 'HDMI-2')
my_laptop_internal_monitor=$(xrandr --query | grep 'eDP-1')
if [[ $my_laptop_internal_monitor = *connected* ]]; then
    bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9 10
fi
if [[ $my_laptop_external_monitor = *connected* ]]; then
    bspc monitor HDMI-2 -d 1 2 3 4 5 6 7 8 9 10
fi

bspc config border_width         1
bspc config window_gap           0

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       true
bspc config focus_follows_pointer true

bspc config focused_border_color "#FEA44C"
bspc config normal_border_color  "#272a34"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a zoom state=floating

# Running stuff
~/.config/polybar/launch.sh &
/usr/libexec/polkit-gnome-authentication-agent-1 &
killall nm-applet || true
nm-applet &
killall pasystray || true
pasystray &
killall xfce4-power-manager || true
xfce4-power-manager &
blueman-applet &
picom --config ~/.config/picom.conf --experimental-backends &
feh --bg-fill ~/Pictures/wallpapers/nenie5.jpg &
# ~/devel/scripts/autolock &
setxkbmap -layout us,th
setxkbmap -option 'grp:win_space_toggle'
setxkbmap -option 'grp:alt_shift_toggle'
