#!/bin/sh

    
case "$(echo -e "Shutdown\nRestart\nLogout\nSuspend\nLock" | dmenu \
    -nb "#202734" \
    -nf "#CBCCC6" \
    -sf "#191E2A" \
    -sb "#BAE67E" \
    -i -p \
    "Power:" -l 5)" in
        Shutdown) exec loginctl poweroff;;
        Restart) exec loginctl reboot;;
        Logout) bspc quit;;
        Suspend) exec loginctl suspend;;
        Lock) exec i3lock -i ~/Pictures/wallpapers/sumikko1_2k_lock.png;;
esac
